name: mediaindex_dart
description: mp4 and webm media files sidx segment and ebml box parser for dart
version: 0.0.2
repository: https://github.com/suconghou/mediaindex-dart
homepage: https://github.com/suconghou/mediaindex-dart
environment:
  sdk: '>=2.15.1 <3.0.0'
  