name: mediaindex_dart
description: media sidx and ebml parser for dart
version: 0.0.1
repository: https://github.com/suconghou/mediaindex-dart
homepage: https://github.com/suconghou/mediaindex-dart
publish_to: https://pub.dev
environment:
  sdk: '>=2.15.1 <3.0.0'
  